### ISSUE TITLE
Unhandled exception while trying to read sarif v2 log file

### ISSUE THREAD

**Issue by abonie** [Microsoft/sarif-sdk#1014]
Following instructions from the "how-to" section I get an exception of type `Newtonsoft.Json.JsonReaderException` while trying to read sarif v2 file. I am using Sarif.Sdk version 1.7.5 installed with NuGet.

**Comment by Evmaus-MS** [comment]
You'll need to use the prerelease 2.0.0-csd.1 package to parse the current SARIF v2 files.  You should be able to consume it from NuGet using a recent version of VS or NuGet.exe that supports semver versioned packages.

The SARIF SDK version 1.7.5 only supports Sarif v1.

Hope this helps!
Everett
