### ISSUE TITLE
Downgrade JSON.NET package to v9

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-sdk#1033]

**Comment by michaelcfanning** [comment]
@EasyRhinoMSFT, what's the rationale for making this change? Did you uncover an issue?

**Comment by EasyRhinoMSFT** [comment]
v9 is included in VS, and if you try to include a different version with your extension, msbuild will override and leave it out. Prior to the 15.8 release of VS, there was a build task that we used to disable this behavior. I contacted the vsix experts DL you gave me and they explained everything. I'll fwd the thread.

**Comment by EasyRhinoMSFT** [comment]
Fixed in #1084
