### ISSUE TITLE
"Cannot evaluate JSON pointer"

### ISSUE THREAD

**Issue by ghost** [Microsoft/sarif-sdk#1066]
**Repro:**

Run the validator on the Sarif.Sdk log provided by @michaelcfanning:
```
Sarif.Multitool.exe validate ^
    --json-schema Sarif.schema.json ^
    --output SarifSdk.validation.sarif ^
    SarifSdk.sarif
```
**Expected:** Tool runs successfully

**Actual:** Tool runs to completion, but the output includes:
```
error ERR998.ExceptionInAnalyze : SARIF1001 : An exception was raised analyzing 'SarifSdk.sarif'
for check 'DoNotUseFriendlyNameAsRuleId' (which has been disabled).
The exception may have resulted from a problem related to parsing the analysis target,
and not specific to the rule, however.
(Cannot evaluate JSON pointer "/runs/0/resources/rules/cs~1unsafe-deserialization"
because the object at "/runs/0/resources/rules" does not contain a property named
"cs/unsafe-deserialization".
Parameter name: referenceToken)
```
I don’t think this is rule-specific; I think it is related to the treatment of rule ids that contain a forward slash.

**Comment by lgolding** [comment]
No, the problem is not related to rule ids containing a forward slash. All the rules in the Sarif.Sdk.sarif log file have ids of the form `cs/xxx`.

**Comment by michaelcfanning** [comment]
mere anarchy is loosed upon the world.
