### ISSUE TITLE
Ensure "not yet autogenerated" build feature works in VS 2017 project system

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#1101]
We might have to rework it because the VS 2017 picks up all source files by default, so it might try to get both copies, the one in `Autogenerated` and the one in `NotYetAutogenerated`.

@michaelcfanning  @rtaket FYI

**Comment by michaelcfanning** [comment]
the way it works is that the targets files generates content to Autogenerated, then we copy over NotYetAutogenerated onto it. Only Autogenerated is picked up for compilation. Should work.

**Comment by lgolding** [comment]
Fixed by @michaelcfanning.
