### ISSUE TITLE
Add an optional property to ruleDescriptor which specifies the location of the online definition of the rule

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#124]
It would be nice if ruleDescriptor had a URI property which specifies an endpoint where the rule definition can be retrieved from. 

In our meeting, we had a deeper conversation about how this property could be used. In general, we thought the URI (and it's contents) can be thought of as a contract for a rule. For example, if the URL was http://sarif.microsoft.com/codedefects/unusedusingstatements, this indicates that the rule professes to validate that there are no unused using statements. The URI describes the defect and the rule verifies the defect does not exist. The relationship between URI(defects)->rules is not 1-to-1. Many rules may profess to verify a defect. This also implies that many tools may profess to verify a defect.

**Comment by michaelcfanning** [comment]
Opened #174 in the sarif-spec repo to cover this.

https://github.com/sarif-standard/sarif-spec/issues/175
