### ISSUE TITLE
SARIF representations should be driven by JSON scheme

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#13]
The current G4-driven mechanism is not sufficiently expressive for deriving the JSON schema. We should investigate hand-maintaining a JSON scheme and constructing managed serialization helpers from that form.

**Comment by michaelcfanning** [comment]
@lgolding 
you can close this. Yay!

**Comment by lgolding** [comment]
Yeah! Json.Schema.ToDotNet FTW.
