### ISSUE TITLE
Is there support (or planned support) for natively handling localized message formats?

### ISSUE THREAD

**Issue by mhuguet** [Microsoft/sarif-sdk#1308]
We have a requirement for localized versions of message formats. See the screen shot for how we've done this today. Are there plans for native support in the SDK and Standard.
![image](https://user-images.githubusercontent.com/12263630/53349136-0b02ad80-38e2-11e9-9d09-2d6566106b7c.png)

**Comment by lgolding** [comment]
Hello @mhuguet , you'll be happy (I hope!) to know that @michaelcfanning and I, along with @kupsch from the SARIF Technical Committee, have spent the past couple of days hammering out a design for localization and we're about to submit it to the TC to vote on. (Actually the three of us are going to discuss it again tomorrow morning, so this might change, but I think its broad outlines will survive.)

Please be aware of a couple of things:
- I have only included aspects of the design that directly correspond with your example above. There is much more to the design than you see here. That is why the design seems much more complex and deeply nested than your example above would seem to require. I'm happy to discuss the design with you in its full glory :-)
- The design is built on top of the most recent version of the spec (January 24th), so many of the objects look different from your example above. I hope it's understandable, but again, feel free to get in touch for any explanation you need.

```
{
  "$schema": "http://json.schemastore.org.sarif-2.0.0",
  "version": "2.0.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "CustomizationAdvisor",
          "guid": "<driver guid>"
          "ruleDescriptors": [
            {
              "id": "web-use-client-context",
              "guid": "<rule guid>",
              "messageStrings": {
                "message1": {
                  "text": "The English message: {0}."
                }
              }
            }
          ]
        }
      },
      "translations": [
        {
          "language": "es-ES",
          "toolComponentTranslations": [
            {
              "guid": "<driver guid>",
              "isPartialTranslation": true,
              "ruleDescriptorTranslations": [
                {
                  "id": "web-use-client-context",
                  "guid": "<rule guid>",
                  "messageStrings": {
                    "message1": {
                      "text": "The Spanish message: {0}."
                    }
                  }
                }
              ]
            }
          ]
        }
      ],
      "results": [
        {
          "ruleId": "web-use-client-context",
          "rulePointer": "driver/ruleDescriptors/0",
          "message": {
            "messageId": "message1",
            "arguments": [ "42" ]
          }
        }
      ]
    }
  ]
}
```

**Comment by mhuguet** [comment]
Thanks a lot!
