### ISSUE TITLE
Consider SarifRewritingVisitor.cs to be auto generated

### ISSUE THREAD

**Issue by harleenkohli** [Microsoft/sarif-sdk#1338]
We have a need to use not-yet-autogenerated version of SarifRewritingVisitor because of the way it handles OriginalUriBaseIds. Solving this issue will let us auto-generate SarifRewritingVisitor.cs.

code snippet:

// NOTYETAUTOGENERATED: we have code that isn't capable of processing directories.
                // We need to fix this problem before we can enable all unit tests.
                /*
                if (node.OriginalUriBaseIds != null)
                {
                    var keys = node.OriginalUriBaseIds.Keys.ToArray();
                    foreach (var key in keys)
                    {
                        var value = node.OriginalUriBaseIds[key];
                        if (value != null)
                        {
                            node.OriginalUriBaseIds[key] = VisitNullChecked(value);
                        }
                    }
                }
                */

**Comment by michaelcfanning** [comment]
i fixed it! hooray
