### ISSUE TITLE
DateTime properties must be nullable

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#134]
RunStartTime and RunEndTime are optional, so property type must be `DateTime?`.

**Comment by michaelcfanning** [comment]
We can do without this if we don't mind users doing a check like so:

if (run.Invocation.StartTime != new DateTime()) // indicates a non-empty DateTime

I suggest we close. ?

**Comment by lgolding** [comment]
I'm really not liking it. Null check is so much more natural. Let me sit with this one for a while.

**Comment by michaelcfanning** [comment]
Don't agree for value types. nullable items lead to unexpected use problems/patterns. Users can also do this

if (runInvocation.StartTime != default(DateTime))

... or ...

if (runInvocation.StartTime != DateTime.MinValue)

**Comment by lgolding** [comment]
Ah, `default(T)` to the rescue. Like it. Ship it. Close it.
