### ISSUE TITLE
Multitool --force option: advertised default is false, actual default is true.

### ISSUE THREAD

**Issue by jeffersonking** [microsoft/sarif-sdk#1340]
Repeat invocations of `smt transform input.sarif --output transformed.sarif` will overwrite the output file.

Expected: Since --force flag was not set, transformed.sarif should not be overwritten.

**Comment by michaelcfanning** [comment]
Not good.

**Comment by lgolding** [comment]
I ran all the multitool commands, and `convert` is the only one that respects `--force`.
