### ISSUE TITLE
Multitool `validate` verb is a silent no-op

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [microsoft/sarif-sdk#1406]

**Comment by michaelcfanning** [comment]
Just curious, why have we created a duplicate issue? Isn't this covered by #1405? :)

**Comment by EasyRhinoMSFT** [comment]
Well 1405 is the PR

**Comment by EasyRhinoMSFT** [comment]
IOW, I think of the PR as a resolution for an issue. So I like having both.

**Comment by michaelcfanning** [comment]
Of course! :) What's wrong with me. I sincerely believed you had created two issues, not a PR and an issue.

**Comment by lgolding** [comment]
Confirmed that the `validate` command is working just fine. @michaelcfanning @EasyRhinoMSFT FYI.
