### ISSUE TITLE
I need to write converters from tool output to SARIF internally. Should I use ToolFileConverterBase?

### ISSUE THREAD

**Issue by mhuguet** [microsoft/sarif-sdk#1473]
We are orchestrating analysis across multiple analysis engines. Some already get converted to SARIF, however, some don't. Would you recommend that I create a custom converter and inherit from ToolFileConverterBase following the same patterns that are being implemented internally with the converters today? I just want to confirm that this is the intention of the pattern before I leverage out outside of that one project.

**Comment by harleenkohli** [comment]
Thanks Mike for reaching out! Yes, using ToolFileConverterBase is intended to be the base class for converters, so your instinct is right. If you don't mind sharing, which tool(s) are you intending to adapt?

**Comment by mhuguet** [comment]
It's a tool internal to Microsoft.
