### ISSUE TITLE
multitool match-results-forward Options have a collision which results in unhandled exception

### ISSUE THREAD

**Issue by harleenkohli** [microsoft/sarif-sdk#1517]
option 'p' is available as both "previousFilePath" or "prettyPrint" (from base class), in run time, if option is provided as -p, we get the following error:

Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element

**Comment by ScottLouvau** [comment]
Previously found as #1498. I have a fix in a working branch and a test to ensure this is caught going forward across all multitool options classes.
