### ISSUE TITLE
FortifyFpr converter produces invalid SARIF 

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#1593]
Convert Test.FunctionalTests.Sarif\v2\ConverterTestData\FortifyFpr\FortifyTest.fpr
Validate result

rule ids are missing, GUIDs don't validate, thread flow locations array is non-unique.

You can also run the UpdateBaselines.ps1 script to regen the current baseline to see the problem

**Comment by lgolding** [comment]
- The invalid GUIDs are the toolComponent id for the CWE taxonomy: it has only 11 digits in the last (12-digit) portion.
- The non-unique arrays are not `threadFlowLocation` objects; they are the string arrays in `threadFlowLocation.kind`, which contain the string `"function"` twice.
- Yes, `rule.id` really is missing and there might not be anything we can do except to repeat the `guid` property.
