### ISSUE TITLE
Enhance property bag testing

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#1673]
Per @michaelcfanning: 

Add tests for the range of types that might occur in a property bag. For example, consider serializing a `double` that exceeds `Int32.Max`. Pass a `float` that is not an integral value. Consider round-tripping a simple custom object. And serialize/deserialize arrays of every supported thing. Understand and test expected behaviors when setting property values to `null` as well.

**Comment by ScottLouvau** [comment]
Roundtripping DateTimes doesn't work today, with or without my change to remove the extra quotes from SerializedPropertyInfoConverter.WriteJson.

It seems SerializedPropertyInfoConverter gets to write the value, but PropertyBagConverter reads the value back, and JsonSerializer.Populate is messing with the DateTime in that case.

**Comment by lgolding** [comment]
@ScottLouvau Roundtripping date/times does work in certain scenarios. PR #1651, which fixed issue #1577, demonstrates one such scenario (going through the `PrereleaseCompatibilityTransformer`), and I have a little test program that demonstrates another one (simple deserialize/re-serialize from a SARIF file).

OTOH I absolutely believe you've seen a real bug, and that it's related to your observation that serialization and deserialization go through different code paths. Do you have a repro that I could put in a failing unit test?

**Comment by lgolding** [comment]
Test program:

```C#
using System.IO;
using FluentAssertions;
using Microsoft.CodeAnalysis.Sarif;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Bug1673
{
    class Program
    {
        static void Main(string[] args)
        {
            string logContents = File.ReadAllText(@"TestData\input.sarif");

            SarifLog log = JsonConvert.DeserializeObject<SarifLog>(logContents);
            string roundTrippedLogContents = JsonConvert.SerializeObject(log, Formatting.Indented);

            roundTrippedLogContents.Should().Be(logContents);

            JObject jObject = JsonConvert.DeserializeObject<JObject>(logContents);
            roundTrippedLogContents = JsonConvert.SerializeObject(jObject, Formatting.Indented);

            roundTrippedLogContents.Should().Be(logContents);
        }
    }
}
```

Input:
```json
{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Bug1673Tester"
        }
      },
      "results": [
        {
          "ruleId": "TST0001",
          "message": {
            "text": "Hello."
          },
          "properties": {
            "date": "2019-09-25T15:07"
          }
        }
      ],
      "columnKind": "utf16CodeUnits"
    }
  ]
}
```

**Comment by ScottLouvau** [comment]
Yes. Re-add DateTime roundtrip to  PropertyBagConverter_RoundTripsStringPropertyWithEscapedCharacters().

This failed when I ran it, but I realized I couldn't fix it.
See https://github.com/microsoft/sarif-sdk/pull/1672/commits/b323c58578c61cbf2277f899ac06efa06ecd34d2#diff-802ec850c9c3388f7307ab9e42c67453L28 for the code to re-add.
