### ISSUE TITLE
SarifWorkItemContext needs to initialize files data

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#1752]
This class should extract source- and non-source-controlled files from the SARIF and populate the SARIF-specific work item model with this data.

**Comment by michaelcfanning** [comment]
@nickmarston, this is checked in yes?

**Comment by nickmarston** [comment]
Finished with https://github.com/microsoft/sarif-sdk/commit/8bcf7e99b0e716e8cc51f65bdad31521af12716e
