### ISSUE TITLE
Can we collapse GH issue creation to a single operation?

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#1790]
Currently it's split between initial creation and then the addition of any labels. Fiddler suggests that you can accomplish both operations in a single request. Octokit API might not support it. Minimally, we need to handle the possibility of a failure between initial creation and subsequent application of labels.

**Comment by eddynaka** [comment]
hi @michaelcfanning , I was looking at the code and the Octokit library and it looks like we can accomplish that:

```csharp
var newIssue = new NewIssue(workItemModel.Title)
{
    Body = workItemModel.BodyOrDescription,
};

newIssue.Labels.Add("label1");
...call create method that is used
```

The only problem that I saw is: if the label doesn't exist, that won't work (https://octokitnet.readthedocs.io/en/latest/issues/#create):
```
Note that Milestones and Labels need to exist in the repository before creating the issue. Refer to the Milestones and Labels sections for more details.
```
