### ISSUE TITLE
Command file-work-items has incorrect error message for using PAT

### ISSUE THREAD

**Issue by chinarosesz** [microsoft/sarif-sdk#1810]
When missing an Azure DevOps PAT, the error message says to set environment variable SarifWorkItemFilingSecurityToken with a valid token. The error message should instruct the user to set environment variable SarifWorkItemFilingPat. 

Steps:

1. Execute the below command.
<code>C:\>dotnet C:\dev\repos\sarif-sdk\bld\bin\AnyCPU_Release\Sarif.Multitool\netcoreapp2.1\sarif.multitool.dll file-work-items "C:\dev\temp\sariftest\original.sarif" --project-uri "https://secretscantest.visualstudio.com/SecToolsEndToEnd"</code>
<code>No security token was provided. Populate the 'SarifWorkItemFilingSecurityToken' environment variable with a valid personal access token or pass a token in a configuration file using the --configuration option</code>

1. Try to set environment variable as instructed in but still fails

**Comment by eddynaka** [comment]
Hi @chinarosesz ,

looking at our resource, i was able to locate the message. But it is already updated:
```
No security token was provided. Populate the 'SarifWorkItemFilingPat' environment variable with a valid personal access token or pass a token in a configuration file using the --configuration option
```

I'm closing the issue, ok?
Thank you!
