### ISSUE TITLE
New rule: Detect use of ".." in file scheme URIs

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#1867]
Even though the SARIF spec v2.1.0 doesn't prohibit it, the use of ".." segments in file scheme URIs is dangerous for reasons explained in oasis-tcs/sarif-spec#461. Add a warning-level analysis rule that reports the presence of ".." segments that are either (a) absolute, using the `file:` scheme, or (b) relative (because the user might resolve them to an absolute URI with the `file:` scheme).

**Comment by eddynaka** [comment]
@shaopeng-gh , can you work on this?

**Comment by shaopeng-gh** [comment]
Got it, will check existing rule format and add a new one.

**Comment by shaopeng-gh** [comment]
Took a deeper look, I found this is already implemented: 
SARIF1002.UrisMustBeValid
https://github.com/microsoft/sarif-sdk/blob/main/src/Sarif.Multitool.Library/Rules/SARIF1002.UrisMustBeValid.cs
possibly we implemented just the issue was not resolved at the time.
