### ISSUE TITLE
New rule: Use Message.id and arguments instead of Message.Text for results messages.

### ISSUE THREAD

**Issue by harleenkohli** [microsoft/sarif-sdk#1891]
User messages (in result message object ) should be referenced from rules array instead of using local value provided in "text" field. This rule is useful for bug logging scenarios when baselining is necessary.

Example:

Undesirable pattern:

```
"results": [
  {
    "ruleId": "TST1001",
    "message": {
      "text": "There is a problem in file 'foo.cs'."
      ]
    }
  }
]
```

desirable pattern:
```
"rules": [
  {               # A rule object
    "id": "TST1001",
    "defaultConfiguration": {
      "enabled": true,
      "level": "note"
    },
    "messageStrings": {
      "default": { # A MultiformatMessageString object
        "text": "There's a problem in file '{0}'." 
      }
    }
  }
]

"results": [
  {
    "ruleId": "TST1001",
    "message": {
      "id": "default",
      "arguments": [
        "foo.c"
      ]
    }
  }
]
```

**Comment by eddynaka** [comment]
@harleenkohli / @lgolding , below the validations that i was thinking:

- if result.message is null => we have a problem
- if result.message.text is not null => we have a problem
- if result.message.id is not null
  - rules = null or rules.count = 0 => we have a problem
  - result.message.id doesnt exist in rules.id => we have a problem
  - result.arguments.count != rule.text.arguments.count => we have a problem

What do you think?

**Comment by lgolding** [comment]
Looks mostly good.

- `result.message` is a required property (see [here](https://github.com/microsoft/sarif-sdk/blob/27c069ea536ee5298ea1737de360aa7f71e9ba4e/src/Sarif/Schemata/sarif-2.1.0-rtm.5.json#L2268) in the schema), so you don't have to check for that. The validator reports schema violations, and halts, before it evaluates any of the `SARIF` rules.
- The first two sub-bullets (`rules` is `null` or `rules.count` is 0, and `result.message.id` doesn't exist) should be covered with a single result message (for example, `The rule metadata doesn't include the message id value `{0}`.)

**Comment by lgolding** [comment]
This is now covered by `SARIF2002.ProvideMessageArguments`.
