### ISSUE TITLE
New rules: SARIF best practices

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#1900]
Implement a set of validation rules that encode some SARIF best practices:

Recommendation|Rule #|Rule dev|Rule status|Doc dev|Doc status|Notes
----------|-----------|-------|------|-------|--------|-----------
No static user-facing strings|1023|@harleenkohli|In progress|@lgolding|Done|
Message arguments|1022|@eddynaka|In progress|||
Enquote dynamic args||||||
Provide tool version|1021|@harleenkohli|In progress|@lgolding|Done|
Express paths relative to source enlistment|||||||
Provide must current `$schema`|1020|@eddynaka|Done|@lgolding|Done|
Concise tool name||||@lgolding|In progress|
Artifacts array must add value|||||||
Version control provenance present||||||Required for work item filing
Provide snippet||||||Appears in web viewer
Provide context region||||||
Detect dead links||||||For rule help ids, at least.
Provide help URIs||||||Important for work item filing
Use conventional names for `uriBaseId`s||||||`SRCROOT`, `BINROOT`, `REPOROOT`...
Use conventional opaque id format||||||`[A-Z]{2,*}[0-9]{4}`
Array references should include minimal information for local readability||||||

**Comment by lgolding** [comment]
This is done. We continue to add new rules and refine existing ones.

@michaelcfanning @eddynaka @harleenkohli FYI

**Comment by michaelcfanning** [comment]
Well done team! Awesome collaboration and progress.
