### ISSUE TITLE
Allow result message to be truncated

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#1915]
The extension method `Result.GetMessageText` takes an optional parameter `bool concise` (default: `false`) which truncates the message to the first sentence. Provide an additional optional parameter `int maxLength` (default: `120`?) to truncate the message before the end of the first sentence if the sentence is too long.

**Comment by lgolding** [comment]
I used a default of 200.

**Comment by michaelcfanning** [comment]
If `concise` is true, i think 128 characters might be better. A concise setting is likely preparing for use in something like the VS IDE error list. 200 chars may be a bit wide as a default for that scenario. ?
