### ISSUE TITLE
npx @microsoft/sarif-multitool <args> fails on Linux

### ISSUE THREAD

**Issue by rsenden** [microsoft/sarif-sdk#1963]
Instructions at https://www.npmjs.com/package/@microsoft/sarif-multitool state the following usage instructions:

```
npm i -g @microsoft/sarif-multitool
npx @microsoft/sarif-multitool <args>
```

However on Linux this fails with an error like the following, because the module tries to execute a native executable that doesn't have the executable flag:

```
/bin/sh: 1: /usr/local/lib/node_modules/@microsoft/sarif-multitool/node_modules/@microsoft/sarif-multitool-linux/Sarif.Multitool: Permission denied
```

This behavior was observed on Ubuntu for Windows, and on a GitHub-hosted Ubuntu runner.

A simple `chmod +x ...` fixes this error, however this step is not documented, and preferably the module should take care of this by itself, without requiring users to manually change permissions in some global node modules directory.

**Comment by jeffersonking** [comment]
@rsenden Agreed this should not require manual integration.

I have intermittently run into this issue. I have seen cases where the binary unpacks with executable permissions and other cases while it does not. The plan was to take a closer look at the moment we pack them to see if we can get it right up front. Fallback will be a post-install `chmod`. We will increase the priority of the investigation. Thanks!
