### ISSUE TITLE
Refinement to SARIF2010.ProvideCodeSnippets: Don't report if embedded content is present

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2003]
@michaelcfanning What's your opinion on this? One could argue that the snippets should be present anyway, so in case the user strips out the embedded content, the snippets will remain behind.

**Comment by michaelcfanning** [comment]
No, I don't think we should recommend redundancy of representation, it's antagonistic to our 'optimize for compactness' goals.

If there's embedded content, there's no need to report the absence of a snippet, because all of the file source is available to the viewer. So I agree with the bug.
