### ISSUE TITLE
Refinement to SARIF2010.ProvideCodeSnippets: Don't report if file is binary

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2004]
If we can detect that the file is binary, either by `artifact.mimeType` or by the filename extension, don't complain about missing snippets.

@michaelcfanning, what's your opinion on this?

**Comment by lgolding** [comment]
I see that the `InsertOptionalDataVisitor` explicitly refrains from emitting snippets for binary files, so if we don't make this change to the analysis rule, we need to fix the visitor, because otherwise there's no hope of this rule passing for binary files.

**Comment by michaelcfanning** [comment]
Yes, certainly, a snippet isn't a good default requirement for a binary file.

**Comment by eddynaka** [comment]
@lgolding , with our last merge, this is easier to accomplish. But, i would like to know:
- what mimeTypes should we look for to ignore?
- what extensions should we look for to ignore?

My idea:
```csharp
foreach (Artifact artifact in this.artifacts)
{
    // Content/text doesn't exist, continue to next
    if (string.IsNullOrEmpty(artifact.Contents?.Text))
    {
        continue;
    }

    // validate mimetype / extension
    if (validation)
    {
        continue;
    }

    // rest of our current code
}
```

**Comment by lgolding** [comment]
The SDK has a static method `MimeType.DetermineFromFileExtension`. It's a heuristic, of course.

**Comment by lgolding** [comment]
It also has `MimeType.IsTextualMimeType` and `.IsBinaryMimeType` that you can use if you have the MIME type available.

**Comment by eddynaka** [comment]
ok! i will draft something and we can discuss there! thanks for the guidance.

**Comment by eddynaka** [comment]
Hello,

I think we solved this issue with this PR: https://github.com/microsoft/sarif-sdk/pull/2031

I added the following section:
https://github.com/microsoft/sarif-sdk/blob/38847ee992148f24e51cb141d45170f2c8931b8c/src/Sarif.Multitool.Library/Rules/SARIF2010.ProvideCodeSnippets.cs#L106-L110

**Comment by lgolding** [comment]
I agree.
