### ISSUE TITLE
sarif-multitool validate fails with ERR997.NoValidAnalysisTargets

### ISSUE THREAD

**Issue by maroneze** [microsoft/sarif-sdk#2055]
I installed the multitool on Linux via npm:

    npm i @microsoft/sarif-multitool

If I run `validate` on a local file, `report.sarif`:

    npx @microsoft/sarif-multitool validate report.sarif

The tool fails with an error:

```
Analyzing...
SARIF.MULTITOOL : error ERR997.NoValidAnalysisTargets : No valid analysis targets were specified.

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: NoValidAnalysisTargets
```

The error message is identical if we omit `report.sarif` from the command line, which is very confusing.

Luckily, a colleague had identified the issue and was able to tell me that a `./` must be added to the filepath:

    npx @microsoft/sarif-multitool validate ./report.sarif

In this case, the tool works. But this behavior is impossible to guess, since it is contrary to command-line conventions. The `validate --help` message does *not* mention it at all, and its only description of the non-option argument is:

    value pos. 0                        One or more specifiers to a file, directory, or filter pattern that resolves to one or more binaries to analyze.

`value pos. 0` is a strange way of specifying arguments; the "specifier to a file, ..." does not mention the need to have a `./` in the path; plus the fact that "resolves to one or more binaries" is incorrect: the sarif file is a text file, not a binary. All of this leads to confusion and provides no clue to the actual issue.

In hopes that Google will help future users understand the error, or that a less surprising behavior will be implemented, I'm creating this issue.

**Comment by lgolding** [comment]
Thanks for the report, @maronze. @jeffersonking (who created the npx package), do you understand this behavior?

**Comment by maroneze** [comment]
Please note that my colleague used the `dotnet`-based tool and had the same issue, so I'm not sure it's npm-exclusive.

However, I'm using Fedora 32, so I'm currently unable to install .Net SDK 2.1, which seems to be the only version compatible with sarif.multitool, so I cannot test it myself. But he's the one who told me about putting the `./` in the PATH, and he used the `dotnet` command.

**Comment by jeffersonking** [comment]
@maroneze Thanks for reporting. I was able to reproduce the issue, will investigate, and keep you posted.

**Comment by jeffersonking** [comment]
@maroneze Your colleague that used the "dotnet"-based tool, which platform was he on?

I can confirm this issue is unrelated to NPM/NPX. The issue reproduces when calling the Multitool binary directly. I was able to reproduce on MacOS. I was not able to reproduce on Windows.

@lgolding We will need to debug how the Multitool resolves relative paths on non-Windows platforms. At a glance, it's not clear to me where/when the resolution takes place.

**Comment by jeffersonking** [comment]
Guessing the bug is in [`FileSpecifier`](https://github.com/microsoft/sarif-sdk/blob/9870138f27c2676498a9ec49c42efc6bea9b872a/src/Sarif.Driver/FileSpecifier.cs#L62). The backslash is not platform agnostic (wasn't intended to be). Actually I don't think the path separator is needed.

**Comment by eddynaka** [comment]
Hi all,
I have created a branch and tested this. Changing the `FileSpecifier` to use the correct slash solved the problem:

![image](https://user-images.githubusercontent.com/16199012/96440639-a561e400-11de-11eb-9e13-305c07cac484.png)

I'm running this on a WSL2 Ubuntu 20.04.
