### ISSUE TITLE
ESLint.Formatter - Add eslint version to run.tool.driver

### ISSUE THREAD

**Issue by tosmolka** [microsoft/sarif-sdk#2070]
We would like to add ESLint version into `tool.driver.version`. According to sarif spec, this property is optional. In our case, this will help us with reporting later on, when processing large number of sarif files from multiple projects. 

Also, this will avoid following validation error from Sarif.Multitool:

`warning SARIF2005: runs[0].tool.driver: The tool 'ESLint' provides neither a 'version' property nor a 'semanticVersion' property. Providing a version enables the log file consumer to determine whether the file was produced by an up to date version, and to avoid accidentally comparing log files produced by different tool versions.`

I have linked a small PR as a proposal, let me know what you think. Thanks.

**Comment by lgolding** [comment]
Fixed in a22af18.
