### ISSUE TITLE
Generalize and harden the export-docs command

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2080]
The method `ExportRulesDocumentationCommandBase` makes certain assumptions which were valid in the context of the SARIF validator – because we controlled all the analysis rule classes – but which might not be valid for all tools that implement the `export-docs` command:

1.	The description is taken from `rule.FullDescription`. But `FullDescription` might be absent and only `ShortDescription` present – or no description at all.
2.	It assumes a particular format for the result message string identifiers (underscore-separated identifier, with the last segment being the “friendly name”).
3.	It always displays the `Text` of the description and the rule messages, but if `Markdown` is available it should be preferred.

**Comment by eddynaka** [comment]
Hi @lgolding ,

I have some questions:
1. If rule.FullDescription == empty -> rule.ShortDescription
    If rule.ShortDescription == empty -> Are we going to remove the description section?

2. Should we print the entire name? So no split.

3. ok.

**Comment by lgolding** [comment]
1. Let's ask @michaelcfanning. If there is neither a `FullDescription` nor a `ShortDescription`, it might be a good idea to have a Description section that says "No description available." That might motivate tool authors to provide rule descriptions.

2. I suggest that you match the rule id against a Regex

    `@"^(?<level>Error|Warning|Note)_(?<friendlyName>[^_]+)$"`

    If it matches, display the `friendlyName` portion. Otherwise, display the whole thing.

**Comment by michaelcfanning** [comment]
Sounds right to me. In general, I think this is a useful strategy to help lead tool developers to provide data that enriches various experiences. For some scenarios (such as bug filing), we could consider being a bit more assertive/precise in our text, e.g. '[Tool did not provide a rule help URL]'. This kind of text would naturally lead customers to request the missing data be supplied, w/an understanding of whose responsibility it is.

@alisonmaclellan

**Comment by lgolding** [comment]
@eddynaka While you're in here, would you please fix a problem with `--output-file-path`: if you don't supply it, it crashes:
```
C:\dev\sarif-visualstudio-extension>sarif export-validation-rules-documentation
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.CodeAnalysis.Sarif.Driver.ExportRulesDocumentationCommandBase`1.Run(ExportRulesDocumentationOptions options)

C:\dev\sarif-visualstudio-extension>
```
The option help text says it should default to `Rules.cmd` in the current directory.

@michaelcfanning What do you think in general of having defaults for output file paths? I'm not a fan. If I run `sarif export-validation-docs` and it silently succeeds, I'll wonder (at least the first time) where the output went. I'd prefer having output file path options be `Required`.
