### ISSUE TITLE
Make pretty-print the default output format

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2098]
The default non-pretty-print behavior produces files that can't be opened by VS Code.

Requested by @roywill

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Let's make this fix a priority. It's a small change.

**Comment by lgolding** [comment]
1. Analysis tools built on the SARIF Driver framework (such as the Multitool's `validate` command) derive from the driver's `AnalyzeCommandBase` class, which uses the `SarifLogger`. The `SarifLogger` ctor accepts an `AnalyzeOptionsBase` object, which derives from `CommonOptionsBase`, whose `PrettyPrint` defaults to `false`.

    What happens if we change the default to `true`? Does the `CommandLineParse` package we use have a syntax like `--pretty-print:false` to turn it off?

2. Converters derive from `ToolFileConverterBase`, whose `Convert` method accepts an `IResultLogWriter`. The Multitool's `convert` command ultimately creates a `ResultLogJsonWriter`, which is configured with a Newtonsoft `JsonTextWriter` whose `Formatting` property comes from the `ConvertOptions` `PrettyPrint` property.

    So defaulting `PrettyPrint` to `true` would address this case, too, but again there's the question of how to unset it.

    NOTE: @roywill is concerned about direct production, not conversion.

A radical approach would be to replace `--pretty-print` with a flag `--minimized` of the opposite sense, but there are lots of scripts out there that use `--pretty-print`. This would be a major breaking change.

**Comment by michaelcfanning** [comment]
1. Add a `minified` argument (note the proposed change in arg name in addition to --pretty-print.
2. If both minified and pretty-print are absent on the command-line, then set logging to pretty-print.
3. If both minified and pretty-print are present on the command-line, then throw.

The should work without breaking anyone.

**Comment by lgolding** [comment]
Beautiful.

**Comment by lgolding** [comment]
@michaelcfanning Good news. `sarif rewrite` with no other arguments than the input file and one of `--pretty-print` or `--minified` does indeed just rewrite the input file with no other changes (except it does fill in `run.columnKind`). Is that ok?

Also: How about `minify` rather than `minified`? `--pretty-print` is an imperative verb (otherwise it would have been "`--pretty-printed`", so it would be `minify` for consistency.

**Comment by roywill** [comment]
Thanks
