### ISSUE TITLE
Sarif.Multitool can't read CppCheck XML version 2

### ISSUE THREAD

**Issue by airtower-luna** [microsoft/sarif-sdk#2103]
I'm trying to use Sarif.Multitool to convert CppCheck output to SARIF. Unfortunately the expected XML structure doesn't match what current CppCheck versions produce, presumably because they now exclusively produce the CppCheck XML format version 2.

Example code:

```c
#include <stdio.h>
#include <sys/socket.h>

int main()
{
	int i;
	printf("%d\n", i);
}
```

Analyzing this code with the command `cppcheck --enable=all --xml` leads to the following output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.1"/>
    <errors>
        <error id="uninitvar" severity="error" msg="Uninitialized variable: i" verbose="Uninitialized variable: i" cwe="457">
            <location file="/test/test.c" line="7" column="17"/>
            <symbol>i</symbol>
        </error>
        <error id="missingIncludeSystem" severity="information" msg="Cppcheck cannot find all the include files (use --check-config for details)" verbose="Cppcheck cannot find all the include files. Cppcheck can check the code without the include files found. But the results will probably be more accurate if all the include files are found. Please check your project&apos;s include directories and add all of them as include directories for Cppcheck. To see what files Cppcheck cannot find use --check-config."/>
    </errors>
</results>
```

Both the `<symbol>` element and the `<error>` element without child elements (the `missingIncludeSystem` one) cause exceptions in Sarif.Multitool when trying to convert the file:
```
System.Xml.XmlException: Could not parse CppCheck location node; element name was not 'location'. Line 7, position 14.
```
And after removing the `<symbol>` element (causing the line number to shift):
```
System.Xml.XmlException: A CppCheck entry must have a nonzero number of locations. Line 9, position 7.
```
After removing the second `<error>` element as well the XML can be converted.

I'd very much appreciate if you could update the CppCheck XML parser. :slightly_smiling_face:

**Comment by eddynaka** [comment]
@airtower-luna , looking at the code, for each error sarif.multitool expects to find locations.

If it doesn't find it, it will throw. Is that xml right?

**Comment by airtower-luna** [comment]
That XML is exactly what CppCheck produces for the example if `--enable=all` is given on the command line. I've tested that with CppCheck packages from Ubuntu 20.04 (CppCheck 1.90) and Debian Unstable (CppCheck 2.1, they've updated to 2.2 since). The [CppCheck documentation](http://cppcheck.sourceforge.net/manual.pdf) (chapter 8) unfortunately isn't clear on whether each `<error>` element will contain a `<location>`, but the actual behavior says no to that.

The error without location is related to the CppCheck configuration, not the code itself, so it's debatable whether it needs to be included in SARIF output. I personally think the converter shouldn't discard any information, and a user might want to adjust their configuration to avoid or disable that warning. Either way it should not make the converter crash. :slightly_smiling_face:

**Comment by airtower-luna** [comment]
Works just fine now with 2.3.7, thank you! :slightly_smiling_face:

**Comment by eddynaka** [comment]
Thanks for letting us know!
