### ISSUE TITLE
GitHelper: Allow client to explicitly set git.exe location

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2105]

**Comment by eddynaka** [comment]
@cfaucon  @michaelcfanning , looking at the current `GitHelper.cs`, I thought in two options:
- create an overload for the constructor
- create a new method that enables the user to set the path

what do you think?

**Comment by eddynaka** [comment]
@cfaucon @michaelcfanning , based on the e-mail thread.

Just created a PR enabling the setter. That would solve the issue as well.

Let me know what do you think.
