### ISSUE TITLE
Update apply-policy command to accept/apply an external policy file

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#2139]
@eddynaka

**Comment by eddynaka** [comment]
Hi @michaelcfanning , just to be sure:
- the parameter will be a path. This path will be a json file which will contain the policies property only. Is that right?

If the sarif that I'm analyzing contains policies as well, what should prevail? The external or internal?

The design that I was thinking:
```csharp
public void ApplyPolicies(string policiesPath)
{
  // convert policiesPath to IList<ToolComponent> and call method belo
}

// changing the first method that we developed, adding a default policies, which would use the policies
// that the run property contains. 
public void ApplyPolicies(IList<ToolComponent> policies = null)
{
  // process all policies
}
```
