### ISSUE TITLE
Don't format the Sarif\Autogenerated directory

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2175]
When we build the SDK _as a submodule of the viewer_, the dotnet-formatter runs and modifies every file in the Sarif\Autogenerated directory. That means that if the viewer is in turn included as a submodule of another project (as it is in fact included by one of our internal projects), then every time we build the viewer submodule, we get this:

```
C:\dev\SarifInternal>git status
On branch users/lgolding/solution-project-tests
Your branch is up to date with 'origin/users/lgolding/solution-project-tests'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   submodules/sarif-visualstudio-extension (new commits, modified content)

no changes added to commit (use "git add" and/or "git commit -a")

C:\dev\SarifInternal>git diff submodules/sarif-visualstudio-extension
diff --git a/submodules/sarif-visualstudio-extension b/submodules/sarif-visualstudio-extension
index 5ae603b..cdde1f6 160000
--- a/submodules/sarif-visualstudio-extension
+++ b/submodules/sarif-visualstudio-extension
@@ -1 +1 @@
-Subproject commit 5ae603bf4aac9d1bd790fdef08e11e8a92befcfe
+Subproject commit cdde1f61cdcbd910ab925e910e625842cb91c810-dirty

C:\dev\SarifInternal>
```

Note the "modified content" and the "dirty". Now I can’t commit that change to the root project.

To work around this, I have to go into C:\dev\SarifInternal\submodules\sarif-visualstudio-extension\src\sarif-pattern-matcher\Src\sarif-sdk and do “git restore .” I have to do this every time I build the viewer submodule.

@michaelcfanning @eddynaka

**Comment by eddynaka** [comment]
Hi @lgolding , i fixed those with the following PRs:
https://github.com/microsoft/sarif-sdk/pull/2176
https://github.com/microsoft/sarif-pattern-matcher/pull/15

I still have to update the visualstudio-extension and test it the sarifinternal. Will keep you updated

**Comment by eddynaka** [comment]
Adding more related prs:
https://github.com/microsoft/sarif-visualstudio-extension/pull/311
