### ISSUE TITLE
Provide a mocking facility for SARIF2006.UrisShouldBeReachable

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#2193]
Currently, our unit tests invoke an actual web client that verifies reachability of test files that we pass to the validator. This approach is causing non-deterministic test failures (as a URI somewhere in our test code happened to be having some problems with availability).

We should use a mock object during testing instead. Because there's no good way to parameterize this rule, my suggestion is to:

1. Create an interface, IHttpClient::Get(uri) which returns a bool.
2. Create a simple wrapper object for the product code which wraps an HttpClient instance. Note that this wrapped instance could itself handle the caching that is currently driven by s_checkedUris.
3. Add an internal static field to the rule that in most cases holds an instance of this wrapper. In test code, we can inject a mock object instead. The property probably should be declared as thread-static.

Open to other approaches, this is the first thing that occurs to me. One thing: let's keep the mockable interface very simply, i.e., don't try to burn the async pattern. We don't need to return a complete HttpResponseMessage either, since we only consume its IsSuccessStatusCode property currently.

@eddynaka, another good opportunity to @yongyan-gh to spin up?

~~~
            HttpResponseMessage httpResponseMessage = s_httpClient.GetAsync(uriString).GetAwaiter().GetResult();
            s_checkedUris.Add(uriString, httpResponseMessage.IsSuccessStatusCode);
            return httpResponseMessage.IsSuccessStatusCode;
~~~

**Comment by yongyan-gh** [comment]
@michaelcfanning should we keep cached s_checkedUris in the rule implementation? or move it to http client wrapper?
according to @eddynaka this caching logic is only for the rule SARIF2006.UrisShouldBeReachable

pls refer to the PR https://github.com/microsoft/sarif-sdk/pull/2200#pullrequestreview-557759418
