### ISSUE TITLE
Author a 'remove duplicate results' command

### ISSUE THREAD

**Issue by MattHoehnen** [microsoft/sarif-sdk#2279]
Provide a mechanism for removing duplicate results from a SARIF log.  

This useful primitive operation belongs in the SARIF SDK.  Windows intends to use in several scenarios.

Duplicates from the CPP compiler are known to occur in certain situations:
- You will see duplication for template expanded code.  If the template is used for n types, you will see one issue raised per each specialization.
- You will also see duplication for inline functions from headers that are included into multiple sources.

Some duplicates may not appear until multiple per-compilation-unit SARIF logs are merged.

Removing dupes is likely less difficult than avoiding dupes.

Duplicates can be removed in certain situations.  For tools that emit source file, line, column #’s (and range?), the SDK is expected to provide reliable deduplication, at the cost of retaining some state while emitting/merging logs.

SARIF from tools that don’t emit column details are not able to be deduped.  One can never be sure whether one is actually uncovering dupes (due to a merge scenario, for example) or if the tool itself has actually found multiple issues. In general, tools are encouraged to provide intra-line regions.

**Comment by michaelcfanning** [comment]
Thanks for the request. This is an important change and I expect we will get to it within the next couple of weeks.

@eddynaka 
@yongyan-gh
