### ISSUE TITLE
An assembly specified in the application dependencies manifest (Sarif.Multitool.deps.json) was not found

### ISSUE THREAD

**Issue by ankhoria** [microsoft/sarif-sdk#2299]
After installation
`dotnet tool install --ignore-failed-sources --add-source https://api.nuget.org/v3/index.json --global Sarif.Multitool
`
I'm getting:
```
An assembly specified in the application dependencies manifest (Sarif.Multitool.deps.json) was not found:
    package: 'Sarif.Multitool.Library', version: '2.4.2'
    path: 'Sarif.Multitool.Library.dll'
```
when trying to run `sarif` with any arguments

**Comment by eddynaka** [comment]
hi @ankhoria , we already fixed that.
For now, add --version 2.4.1, this will allow you to use the multitool

**Comment by hefloryd** [comment]
I'm using it via https://github.com/microsoft/sarif-actions which is broken atm, unless you know of a way to force it to use 2.4.1? Are you planning to release 2.4.3 soon?

**Comment by eddynaka** [comment]
Got it. Will try to release today.
Since u are using sarif-actions. Are you liking it?

**Comment by hefloryd** [comment]
Yes, it worked really great for merging reports from clang scan-build, which wouldn't display properly on the GH security tab if uploaded as individual files. Thanks for that!

**Comment by eddynaka** [comment]
version 2.4.3 released. soon it will be available.
