### ISSUE TITLE
Add CWE data taxonomies

### ISSUE THREAD

**Issue by yongyan-gh** [microsoft/sarif-sdk#2310]
1) first create a SARIF taxonomy that stores all CWE data
2) this file will need to be published externally on the web
3) now, any SARIF rule can define a taxonomic relationship to one or more CWE rule ids
4) we can emit this data to a SARIF log. we can refer to an externally published taxonomy file, too (as opposed to inlining the CWE taxonomy data into the log)

**Comment by eddynaka** [comment]
Closing, since:
1. we started the work in https://github.com/sarif-standard/taxonomies
2. for now, its already published as raw content from github
3. there are a few examples with relationships between taxonomies
4. this was done in the flawfinder
