### ISSUE TITLE
Multitool does not support transform option

### ISSUE THREAD

**Issue by zendu** [microsoft/sarif-sdk#2329]
Multitool document lists "transform" option to convert files from old to new SARIF format. But latest version v.2.4.5 does not provide such an option. Please fix code or documentation.

**Comment by eddynaka** [comment]
Hi @zendu ,

sorry for that. We changed to rewrite.

Can you try with that?

Will update ASAP.

**Comment by zendu** [comment]
Ohh. Rewrite works. Thanks.
