### ISSUE TITLE
Partitioning is not partitioning the artifacts

### ISSUE THREAD

**Issue by eddynaka** [microsoft/sarif-sdk#2385]
Below is one example
[rust.zip](https://github.com/microsoft/sarif-sdk/files/7206820/rust.zip)

If you partition by rule, each sarif will have 1 rule with 1 result but 2 artifacts.

The ideal SARIF would have 1 rule, 1 result, and 1 artifact each.

@yongyan-gh @harleenkohli @michaelcfanning

**Comment by yongyan-gh** [comment]
The issue occurs when creating vsts work item, after partitioned by PerRun splitting strategy, the partitioned sarif log has 1 result, but have 7 artifacts, and description points to a wrong artifact: 
This work item contains 1 'semmle' issue(s) detected in src/DeploymentLibrary/Common/RobocopyUtility.cs (+7 locations).

There are 2 issues:
1.    all the artifacts are assigned indexes, so they are considered as global artifacts (mentioned out side of any result), and they will be added to partitioned log even they are not mentioned by any result.
see comments here:
https://github.com/microsoft/sarif-sdk/blob/b262841c97859f3bcfb65a652c7035e8ae6087b3/src/Sarif/Visitors/PartitioningVisitor.cs#L353-L357


2.   The result has mentioned couple other artifacts in codeFlows/relatedLocations sections.
e.g total 7 artifacts, 1 is the result's artifacts (src/OneboxWorker/OneboxWorker.cs), and other 4 are mentioned by the result's codeFlows/relatedLocations sections. In this case, should we keep 5 artifacts or just 1? Now the work item description uses first artifact as detected target it may be an artifact in codeflow, not the real target has issue.

>This work item contains 1 'semmle' issue(s) detected in src/DeploymentLibrary/Common/RobocopyUtility.cs (+7 locations)

The RobocopyUtility.cs is not the result's artifact in this case

**Comment by eddynaka** [comment]
@yongyan-gh ,

we could:
1. count the number of results: this would fix the number of artifacts vs. number of results
2. review the path as you mentioned: this would fix the path.
