### ISSUE TITLE
merge produces empty SARIF file regardless of the inputs

### ISSUE THREAD

**Issue by daiyinong** [microsoft/sarif-sdk#2400]
We've been trying to merge a few SARIF files using the merge sub-command but all we have got is an empty file that looks like the following:
{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
  "version": "2.1.0",
  "runs": []
}
We've both tried running the command on all SARIF file under the current directory (*.sarif) and on just one SARIF file. One of the commands we used was npx @microsoft/sarif-multitool merge --force --merge-runs --output-directory=result/ --output-file=MergeResult.sarif *.sarif

We are running this in WSL2 ubuntu. Could you help us find out what we may be doing wrong here?
Thanks!

**Comment by shaopeng-gh** [comment]
update: working on the fix
