### ISSUE TITLE
PHP binding for SARIF SDK 

### ISSUE THREAD

**Issue by llaville** [microsoft/sarif-sdk#2414]
As author of this package https://github.com/llaville/sarif-php-sdk, I would like to share that a PHP binding exists now for the PHP eco-system.
The first version 1.0.0 implement full specification of v2.1.0

As this project is a bit younger, there are probably some errors, wrong implementation, but I'd like to share this solution to the community, especially because I didn't found any solution for PHP yet.

**Comment by eddynaka** [comment]
Hi @llaville ,

thanks for letting us know!
Soon we will have a wiki in the sarif-spec and we can point to your repository as well.

**Comment by llaville** [comment]
Hi @eddynaka 

One year later, what's the status ?

**Comment by eddynaka** [comment]
Hi @llaville ,

The SARIF TC created a draft page in Wikipedia:
https://en.wikipedia.org/wiki/Draft:Static_Analysis_Results_Interchange_Format

Adding @michaelcfanning to be aware.

**Comment by llaville** [comment]
I don't think this report should stay open ! Closing now.
