### ISSUE TITLE
'postUri' command naming convention is wrong

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#2428]
This argument s/be named 'post-uri' to match other names, e.g. 'rich-return-code'

@shaopeng-gh @yongyan-gh, easy issue to fix. Can we make it a priority? This is a breaking change if we've already shipped the previous argument name.

**Comment by shaopeng-gh** [comment]
got it, let me create a PR to update it.

**Comment by shaopeng-gh** [comment]
I see this option was added after latest release, so will not affect user.

**Comment by shaopeng-gh** [comment]
https://github.com/microsoft/sarif-sdk/pull/2429
