### ISSUE TITLE
Links in the scans tab do not resolve references to related locations correctly

### ISSUE THREAD

**Issue by rtaket** [microsoft/sarif-sdk#2525]
Section 3.11.6 of the SARIF specification states that embedded links in messages can refer to a related location using its 'id'. 

The messages for the CodeQL use this mechanism for their DFA rule messages. However, when rendered in the Scans tab, the message links do not point to the source code location referred to in the related location. Instead, they link to https://sariftools.gallerycdn.vsassets.io/extensions/sariftools/scans/0.3.5/1639522921359/1.

This is example 2 from the SARIF specification. In this example, the link to [here] would refer to the URL above, rather than to the source code.

```
{ # A result object (§3.27)
 "ruleId": "TNT0001",
 "message": {
 "text": "Tainted data was used. The data came from [here](3)."
 },
 "locations": [
 {
 "physicalLocation": {
 "uri": "file:///C:/code/main.c",
 "region": {
 "startLine": 15,
 "startColumn": 9
 }
 }
 }
 ],
 "relatedLocations": [
 {
 "id": 3,
 "physicalLocation": {
 "uri": "file:///C:/code/input.c",
 "region": {
 "startLine": 25,
 "startColumn": 19
 }
 }
 }
 ]
}
```

**Comment by michaelcfanning** [comment]
@jeffersonking, did we fix this?

**Comment by jeffersonking** [comment]
The quoted SARIF is malformed. `physicalLocation` does not directly have a property `uri` (it needs `artifactLocation`).  

Looks like a spec bug https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317467. Perhaps it was not updated from v1 to v2?
