### ISSUE TITLE
Support 'IncompatibleRuleIds' in the infrastructure

### ISSUE THREAD

**Issue by yongyan-gh** [microsoft/sarif-sdk#2591]
Please see more details in #2580

>Rules should be able to declare an `IncompatibleRuleIds` set or something similar, All the rule does is to publish this data.
>
>Then we update the analysis engine, which, when instantiating skimmers, makes sure that no new enabled skimmers have a rule id that conflicts with the set of loaded skimmers so far. The analysis engine could raise an error-level configuration notification and exit.
>
>This approach would require users to properly configure analysis to account for the configuration problem. I think everything would drop in pretty cleanly by doing this, we need a low-level update to rules metadata and a simple update to the default skimmer loading behavior.

**Comment by shaopeng-gh** [comment]
Closing the issue with the feature Yong implemented.
https://github.com/microsoft/sarif-sdk/pull/2597
