### ISSUE TITLE
Multitool convert options removed (--force, --pretty-print)

### ISSUE THREAD

**Issue by MarkvanOsch** [microsoft/sarif-sdk#2638]
I noticed that our build is failing because with the upgrade from 4.0.0 to 4.1.0 these commandline options where removed:
--force, --pretty-print

Was this intentional? What is the replacement for these? For example for overwriting an output file.

**Comment by thomas-bc** [comment]
We are facing the same issue, any recommendation for replacing --force? Or is overwriting the default and only behavior now?

**Comment by mpoqq** [comment]
`--force`, `--pretty-print`, `--inline` are replaced by `--log="ForceOverwrite, PrettyPrint, Inline"`.
Unfortunately it is not documented and was not communicated.
I also think this is a breaking change and should be reverted.

**Comment by mpoqq** [comment]
Docu was updated: https://github.com/microsoft/sarif-sdk/pull/2654
https://github.com/microsoft/sarif-sdk/blob/main/docs/multitool-usage.md

@MarkvanOsch Issue can probably be closed

**Comment by shaopeng-gh** [comment]
Thanks for reporting the issue.
@mpoqq thanks for the help here.
closing the issue.
