### ISSUE TITLE
Specified Schema is 404

### ISSUE THREAD

**Issue by gfs** [microsoft/sarif-sdk#2662]
SDK 4.1.0 outputs a schema location of [https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.6.json](https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.6.json) but that link is 404.

![image](https://user-images.githubusercontent.com/98900/235557070-48ca7696-e092-4fcb-bd9c-604fc1de55c9.png)

It looks like this was also reported in [BinSkim](https://github.com/microsoft/binskim/issues/837)

**Comment by shaopeng-gh** [comment]
Acknowledging the problem. We will be able to finalize the rtm 6 ( or removed reference to it if deem not needed ) when we get to the model changes done and it should be published to the schema store when finalized. We don't have an ETA yet.

**Comment by gfs** [comment]
@shaopeng-gh thabks. Assuming I want to generate valid sarifs in the interim - is it better to replace the .6 version with .5 or just the base 2.1.0? Are the .X version sequential errata to the base spec but without changing its version?

**Comment by shaopeng-gh** [comment]
RTM.5 is the latest stable version to use.
The number after RTM e.g.  RTM.5 and RTM.6 are sequential errata to the base spec but without changing its version, yes I believe so.
