### ISSUE TITLE
ConvertToSarif default output filename defaults to ".sarif"

### ISSUE THREAD

**Issue by bobschumaker** [Microsoft/sarif-sdk#378]
"A file path to the converted SARIF log. Defaults to <input file name>.sarif."

In other analysis tool work, I've seen references that Sarif output files should be named ".sarif.json". Is there a preferred naming style for Sarif output files from tools?

**Comment by lgolding** [comment]
@bobschumaker , where is the quoted sentence from? ("A file path to the converted SARIF log. Defaults to .sarif.")

**Comment by bobschumaker** [comment]
Sorry -- it's from the converter argument parser in the Sarif repo (and the code implements that format).

**Comment by lgolding** [comment]
Got it. And I see that both .sarif and .sarif.json are mentioned in the code for the Visual Studio SARIF viewer VSIX:

```
G:\Code\sarif-sdk\src\Sarif.Viewer.VisualStudio\OpenSarifFileCommand.cs(152):
string filter = "SARIF files (*.sarif;*.sarif.json)|*.sarif;*.sarif.json";

G:\Code\sarif-sdk\src\Sarif.Viewer.VisualStudio\SarifFileAndContentDefinitions.cs(22):
[FileExtension(".sarif.json")]
```

This is the only place in the SARIF SDK source code that the string ".sarif.json" appears.

Just so we can get a sense of what the more common choice is right now -- which isn't to say that we'd necessarily abide by it -- do you recall where else you saw ".sarif.json" used?

**Comment by lgolding** [comment]
(My preference would be to settle on .sarif.json so that non-SARIF-aware JSON-processing tools like syntax highlighters and Intellisense would do the right thing.)

**Comment by lgolding** [comment]
@michaelcfanning Do you want to recommend .sarif.json as the filename extension in the spec?

**Comment by michaelcfanning** [comment]
I believe .sarif is best. Viewers like VS sniff the format and detect its JSON. IDEs like VS code provide a simple extensibility model that allow association with JSON language service. otoh, OS's like Windows cannot provide useful associations with multipart extensions.

**Comment by lgolding** [comment]
[So let it be written. So let it be done.](https://en.wikiquote.org/wiki/The_Ten_Commandments_(1956_film)#/media/File:Yul_Brynner_in_The_Ten_Commandments_film_trailer.jpg)

Do you want to change the viewer to not mention ".sarif.json"? Today, it mentions both extensions.
