### ISSUE TITLE
charOffset and byteOffset need to be int? (nullable)

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#40]
It is easy for log consumers to determine that they need to need to consult charOffset or byteOffset members to determine result location, they only need to consult startColumn, which is 1-indexed (if its value is 0, then charOffset or byteOffset must be consulted).

Because charOffset and byteOffset are 0-indexed, however, we cannot distinguish which property is in play for offset == 0. 

The practical impact is that object models (such as provided by the SARIF .NET SDK) must provide nullable values for these properties, that directly express whether the property was present in source JSON.

**Comment by BillyONeal** [comment]
There's no need to distinguish for zero: char offset of 0 and byte offset of 0 are equivalent and point to the beginning of the file.

**Comment by michaelcfanning** [comment]
The issue for this case is how to interpret a non-zero value for length. We previously had a charLength and byteLength but collapsed these into a single property.

**Comment by BillyONeal** [comment]
Would it be OK to just say length is always the byte length? It's much easier to reverse engineer characters from bytes than it is to go the other way around.

**Comment by michaelcfanning** [comment]
we have a single offset property now, all is well.
