### ISSUE TITLE
VSIX: Info Tab: The friendly tool name should be displayed instead of the tool exe name

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#405]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

Expected: The name of the tool, "ModernCop", should be displayed.
Actual: The name of the exe, mod50, is displayed.

See attached screenshot.

![toolname](https://cloud.githubusercontent.com/assets/15946080/16528995/19a7a5ca-3f75-11e6-9635-e585301aeae0.png)

[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343879/AttributeAnalysis.zip)

**Comment by lgolding** [comment]
The friendly name is now displayed:

![image](https://cloud.githubusercontent.com/assets/11762653/16884655/682255e6-4a7f-11e6-851f-8c11d73174a1.png)
