### ISSUE TITLE
VSIX: Info Tab: The section headers should span all the columns

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#406]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

Expected: The section headers should span all the columns.
Actual: The section headers are constrained to the first column. This is making the first column too wide.

See attached screenshot.

![sectionheaders](https://cloud.githubusercontent.com/assets/15946080/16529177/35f5e75e-3f76-11e6-8c66-84c8937da36c.png)
[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343893/AttributeAnalysis.zip)

**Comment by lgolding** [comment]
This is fixed. Current screen shot shows that the headers span columns:

![image](https://cloud.githubusercontent.com/assets/11762653/16890770/8613fd6c-4aa6-11e6-8ea7-26c5e1452bc8.png)
