### ISSUE TITLE
VSIX: Info Tab: The tool version number is displayed twice in the section header

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#407]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

Expected: The tool version number is only displayed once.
Actual: The tool version number is displayed twice.

See attached screenshot.

![duplicateversion](https://cloud.githubusercontent.com/assets/15946080/16529234/9a6bde3c-3f76-11e6-83f9-f6241328293a.png)
[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343896/AttributeAnalysis.zip)

**Comment by lgolding** [comment]
Because we now display the friendly name instead of the full name, the version number only appears once:

![image](https://cloud.githubusercontent.com/assets/11762653/16884671/8225789c-4a7f-11e6-898f-3cfe1166f383.png)
