### ISSUE TITLE
VSIX: Info Tab: The invocation info strings are clipped

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#408]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

Expected: The invocation command line string wraps when it is wider than the screen.
Actual: The invocation command line string is clipped because it is wider than the screen.

See attached screenshot.

![stringclipping](https://cloud.githubusercontent.com/assets/15946080/16529349/40ed543e-3f77-11e6-9d74-e36e06d2ca1b.png)
[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343902/AttributeAnalysis.zip)

**Comment by lgolding** [comment]
The invocation strings now wrap:

![image](https://cloud.githubusercontent.com/assets/11762653/16884631/52377626-4a7f-11e6-97c4-2b145e4412ce.png)
