### ISSUE TITLE
VSIX: Info Tab: The "No additional content" string shouldn't contain a period

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#411]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

Expected: The no additional content string does not end with a period
Actual: The no additional content string contains a period

See attached screenshot.

![noadditionalcontent](https://cloud.githubusercontent.com/assets/15946080/16529620/d14d5a6e-3f78-11e6-90ff-3a43a49e31ba.png)
[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343913/AttributeAnalysis.zip)

**Comment by lgolding** [comment]
The string "No additional content" no longer appears in the UI or anywhere in the repo.
