### ISSUE TITLE
AnnotatedCodeLocation of kind 'call' requires properties for caller and callee

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#415]
SDV provides simple function names for these. But should they be logical locations?

**Comment by lgolding** [comment]
I will file this issue to the spec repo.

**Comment by michaelcfanning** [comment]
per spec issue. the fullyQualifiedLogicalName on the ACL instance represents the caller for a kind of 'call'. we should add a 'callee' member that represents the called item (which is populated only when the kind is call).
