### ISSUE TITLE
IsSuppressedInSource needs to be a bool?

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#43]
In order to express three conditions:

in source suppression information not available (e.g., when CODE_ANALYSIS is not defined)
in-source suppression info available and item is suppressed in source
in-source suppression info available and item is not suppressed in source

**Comment by BillyONeal** [comment]
Is `CODE_ANALYSIS` being defined detectible from the resulting binary? (If so makes sense to me :) )

**Comment by michaelcfanning** [comment]
@lgolding , all these issues that refer to making optional items nullable represent breaking changes for the SDK itself (not the format, obviously). can we close this? seems like all would be addressed by a single change to the generator. this is a jschema change, actually, not a sarif-sdk problem.

**Comment by lgolding** [comment]
Thinking about this, will get back to you in a few minutes,

**Comment by lgolding** [comment]
Well, that was more than a few minutes. :)

Yes, JSchema should emit optional value-typed properties into the object model as `T?`.  It's a simple but not entirely trivial change because I have to make sure the cloning code works properly, but no big deal. I'll file an issue in JSchema.

**Comment by lgolding** [comment]
Filed lgolding/jschema#72.

**Comment by michaelcfanning** [comment]
this will be resolved by updating isSuppressedInSource to consist of an enum value (unknown, true, false) in the standard.

**Comment by lgolding** [comment]
This was fixed by PR #227
