### ISSUE TITLE
Driver framework produces binary analysis-specific message

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#506]
When a skimmer throws an exception that the framework catches, the framework produces a message like this:

errorERR998.ExceptionInAnalyze : SV0003 : An exception was raised analyzing 'G:\Code\sarif-sdk\src\SarifCli.FunctionalTests\TestData\UrisMustBeValid\InvalidUriInFileChange.sarif' for check 'UrisMustBeValid' (which has been disabled). The exception may have resulted from a problem related to parsing image metadata and not specific to the rule, however.

That bit about "parsing image metadata" doesn't apply to all checkers.

**Comment by lgolding** [comment]
@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
just change the phrase to 'parsing the analysis target and not specific to the rule'.

**Comment by michaelcfanning** [comment]
This part looks strange. 
errorERR998.ExceptionInAnalyze : SV0003 
I wouldn't expect SV0003 to appear there

**Comment by lgolding** [comment]
I'll have to look at that.

**Comment by lgolding** [comment]
@michaelcfanning In response to your question about `SV0003`: That is the id of the rule that was being evaluated when the exception occurred. See the call to `LogToolNotification` in `src\Sarif\Errors.cs`, which logs the result of a call to `CreateNotification`, which takes the rule id as one of its arguments.

It would be clearer if instead of just the rule id, the message said "Exception was raised while evaluating rule {ruleId}:".
