### ISSUE TITLE
Is a .net core/standard version planned?

### ISSUE THREAD

**Issue by laedit** [Microsoft/sarif-sdk#540]
I made an application which use Sarif.Sdk and I want to convert it to .net core, so I wonder if a .net core/standard version of Sarif.Sdk is planned?

**Comment by lgolding** [comment]
This is in progress now.

**Comment by lgolding** [comment]
@laedit This work is being tracked by Issue #587, "Provide a .NET Core version of the SARIF SDK", so I'm resolving this one as duplicate of that one (even though this one is earlier in time). It is mostly done.

@jeff-bacon Could you please characterize for Jérémie the status of this work?
