### ISSUE TITLE
Make extension compatible with VS 2017

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#557]
VS 2017 has a new model for VSIXs, called VSIX 3. In response to a question on this [blog post](https://blogs.msdn.microsoft.com/visualstudio/2016/11/16/visual-studio-2017-rc/), Tim Sneath wrote:

> Right now we display a warning message when you install an older extension on Visual Studio, because we want to give extension authors time to adapt to the changes we announced last week here: https://blogs.msdn.microsoft.com/visualstudio/2016/11/10/extensibility-in-visual-studio-15-increasing-reliability-and-performance/.

> There are a number of limitations for older extensions, however, particularly if they make assumptions about the location of the Visual Studio installation or reference assemblies being present in the GAC. As a result, we cannot guarantee the stability of Visual Studio with these extensions installed, hence the warning message. We’re working with extension authors to migrate to use the newer capabilities in VSIXv3 by release.

See also: http://www.visualstudioextensibility.com/2017/01/10/its-time-to-change-the-vsix-manifest-of-your-extension-to-v3-for-visual-studio-2017-compatibility/

**Comment by rtaket** [comment]
Fixed in PR https://github.com/Microsoft/sarif-sdk/pull/565.
