### ISSUE TITLE
File/Open dialog should validate file existence with every directory change

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#56]
When attempting to remap a file location, it is nice when the code automatically tries to locate the remapped file, rather than requiring a use to navigate to it completely. Making this improvement would entail getting a callback from File/Open on any directory change. We'd then need to examine all directory suffixes on the target file path to see if any of them resolve via File.Exists.

**Comment by lgolding** [comment]
Moved to vsix repo
