### ISSUE TITLE
Viewer crashes when selecting issue in a SARIF file

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#567]
1. Open VS 2017
2. Open the attached SARIF file (first, change its extension to .sarif).
3. Open the SARIF Explorer window.
4. Select the single entry in the error list.

Result: "Microsoft Visual Studio 2017 has stopped working".
[CrashOnIssueSelect.sarif.txt](https://github.com/Microsoft/sarif-sdk/files/1006081/CrashOnIssueSelect.sarif.txt)

**Comment by rtaket** [comment]
Fixed in PR https://github.com/Microsoft/sarif-sdk/pull/565.
