### ISSUE TITLE
Viewer crashes when opening a SARIF file

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#568]
1. Open VS 2017.
2. Open the attached SARIF file (first, change its extension to .sarif).

Result: Object reference not set to an instance of an object.
[CrashOnOpen.sarif.txt](https://github.com/Microsoft/sarif-sdk/files/1006088/CrashOnOpen.sarif.txt)

**Comment by rtaket** [comment]
The input file isn't a valid SARIF file. We need to validate the input file before processing it and fail earlier in the process (at load time.)

**Comment by lgolding** [comment]
This no longer repros.

@michaelcfanning @rtaket @vinaykapadia FYI
