### ISSUE TITLE
SARIF Viewer VSIX does not fully match selected Visual Studio theme

### ISSUE THREAD

**Issue by vinaykapadia** [Microsoft/sarif-sdk#598]
1. Set Visual Studio theme to Dark.
2. Open a SARIF file.
3. Click on a line to open the Sarif Explorer window.

Expected:
Sarif Explorer should fully match the Dark theme.

Actual:
Sarif Explorer still shows Light theme. Some text does convert to Dark theme, which makes it mostly unreadable. See attached image. Note that there is text between the "list.cpp (15)" text and the "Locations" tab that is almost too light to read.

**Comment by vinaykapadia** [comment]
![sarif_vsix_theme_bug](https://user-images.githubusercontent.com/17637030/29724777-bb0dd3b8-897e-11e7-823a-b4a073e90ec4.png)

**Comment by EasyRhinoMSFT** [comment]
Resolved by PR #690
