### ISSUE TITLE
Viewer should automatically invoke converters, if available

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#60]
We should add new options to File/Open for our tool converters. E.g., we have an entry for Fortify files that would invoke the converter for Fortify, convert to SARIF, and then populate via regular code paths.

When we have this functionality, the viewer is a kind of universal SA results viewer, might warrant some renaming of commands/change of metadata associated with package.

**Comment by lgolding** [comment]
@michaelcfanning already did this.
