### ISSUE TITLE
File, Open on SARIF file does not bring Error List into view

### ISSUE THREAD

**Issue by komal436** [Microsoft/sarif-sdk#666]
1. Have a Visual Studio Sarif Extension installed.
2. Ensure to have registry setting to open sarif files by default in VS.(Simple way is Run BuildAndTest.ps1).
    or right click on sarif file to open in VS.

Expected: Sarif Log should be seen in the error List window.
Actual: The log is not shown in VS Error List Windows. Need to explicitly drop the file in VS or open from Tools->Open Static Analysis Log File -> Open Sarif File.

If this is already a feature, this could be a bug, else it's will be a feature request.

**Comment by lgolding** [comment]
@komal436 What's actually going on here is that _if the Error List Window_ is not already visible, then Tools, Open Static Analysis Log File, Open Sarif File will make it visible -- but File, Open will not.

If you select menu item View, Error List, then you will see the results from the SARIF file -- no matter how you opened it.

The relevant line of code that executes from the Tools menu, but not from File, Open, is this:
```
SarifViewerPackage.Dte.ExecuteCommand("View.ErrorList")
```

@michaelcfanning I'll spend a little more time on this.
