### ISSUE TITLE
Update all checked in references to Apache license

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#686]
Replace with our MIT license comments:

Sarif.Multitool\Properties\AssemblyInfo.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.Multitool.FunctionalTests\AnalyzeCommandTests.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.Multitool.FunctionalTests\SarifMultitoolTestBase.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.UnitTests\Core\PropertyBagHolderTests.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.UnitTests\Core\StackTests.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.UnitTests\Core\TagsTests.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
Sarif.UnitTests\Readers\PropertyBagConverterTests.cs:// Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

**Comment by EasyRhinoMSFT** [comment]
Resolved with merge 688
https://github.com/Microsoft/sarif-sdk/pull/688
