### ISSUE TITLE
Viewer: support inline links, rather than separate "related links" view

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-sdk#765]
Mend places the link inline in the result message, which is a slightly nicer UI that providing “related locations” in a separate pane, as the SARIF viewer does.

**Comment by EasyRhin0** [comment]
Complexity: this feature can only be done with the 15.0 VS shell library, which contains new build-time checks for certain methods which must be called on the UI thread, Adding the necessary assurance method call (ThreadHelper.ThrowIfNotOnUIThread) breaks about a dozen unit tests.
