### ISSUE TITLE
Need to handle embedded file contents + uri based locations

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-sdk#798]
@EasyRhin0  @EasyRhinoMSFT 

Can you contact me here at Microsoft on this and other issues?

**Comment by EasyRhin0** [comment]
HTTP/HTTPS URLs for source files are in fact supported, but the host domain is restricted to "raw.githubusercontent.com". With this restriction removed, source files are downloaded and opened in the IDE. At that point, however, the error list is cleared, which is incorrect behavior, so investigating that now.

**Comment by EasyRhin0** [comment]
The disappearing error list item is caused by the presence of this property in the result:
  "suppressionStates": [
	"suppressedInSource"
  ]

It just happened to be in the result I was using to test. I'll spend a little time looking for the cause, because this doesn't seem like desirable behavior.
