### ISSUE TITLE
VS Viewer: Null ref exception when opening SARIF w/entries without locations.resultFile

### ISSUE THREAD

**Issue by mhuguet** [Microsoft/sarif-sdk#856]
We run our analysis in some cases against IL (without debug symbols) and are unable to obtain resultFile information so the resultFile node is empty. Below is an example. What we have is use the properties on the locations node to include the module, member, and type, which is usually as precise as we can get it. Please allow for the resultFile node to not exist. I would expect that the behavior in the extension would be that the double click would not do anything, however, I would like to see the metadata including the properties.

{
  "ruleId": "AvoidQueryAllColumns",
  "level": "error",
  "message": "Evaluate the use of AllColumns in ColumnSet constructor call with 'true' argument.",
  "locations": [
    {
      "fullyQualifiedLogicalName": "PC.Plugins.AutoAssignPlugin.GetTeam()",
      "properties": {
        "module": "PC.Plugins",
        "member": "PC.Plugins.AutoAssignPlugin.GetTeam()",
        "type": "PC.Plugins.AutoAssignPlugin"
      }
    }
  ],
  "snippet": "new Microsoft.Xrm.Sdk.Query.ColumnSet(1)",
  "id": "40190a4a-86df-497e-806f-62c8fa4dcdcf",
  "properties": {
    "severity": "High"
  }
}

**Comment by michaelcfanning** [comment]
@EasyRhin0, can you take a look? if we haven't shipped the last v1 VSIX yet, this problem might warrant a fix

**Comment by michaelcfanning** [comment]
@Evmaus-MS fyi

**Comment by EasyRhin0** [comment]
@mhuguet, please send me the log file that's causing the crash. I tried to rig one up but couldn't repro. Thanks!

**Comment by mhuguet** [comment]
I sent it in email @EasyRhin0

**Comment by EasyRhin0** [comment]
The problem is that the run.tool node is null, and that's a required object. How was this log created?

**Comment by mhuguet** [comment]
We have an internal tool that creates it using the SDK. Is there a validate method or something to ensure that we have a valid SARIF file that we output?
