### ISSUE TITLE
We need documentation on how to use the Sarif.Sdk to produce Sarif files

### ISSUE THREAD

**Issue by davidknise** [Microsoft/sarif-sdk#90]
We took a crack at integrating Sarif into two of our prototyping tools and were able to do so, but through trial and error.  Some sample code in the README file for generating a Sarif output file using the SDK would be helpful!

**Comment by michaelcfanning** [comment]
Yes. The SDK needs development here and it would be helpful if the spec provided some guidance on core concepts to express. You have the VS Code extension to validate against the current schema, don't you? I can provide you an experimental VSIX that puts SARIF into the error list, also helpful for debugging problems. @lgolding  and I have discussed creating a SARIF language service in VS that provides more exhaustive validation. Finally, we need to augment our JSON schema to express constructs such as oneOf that are currently absent (an artifact of the automated process we use to produce the schema, which is not sufficiently expressive to cover all JSON schema validation mechanisms). @lgolding  for visibility.

Can you send your sample files to Larry and me?

**Comment by michaelcfanning** [comment]
We now have samples
