### ISSUE TITLE
Transformer: codeFlowLocation.step is mishandled

### ISSUE THREAD

**Issue by EasyRhin0** [Microsoft/sarif-sdk#912]
Zero values are incremented in an attempt to correct zero-based sequences. This doesn't work because the default value is zero (i.e., when the property is omitted). For now, we should discard the code that corrects for zero and simply use whatever value is there. Long term, we should investigate using a nullable int, which would require a codegen change.

**Comment by lgolding** [comment]
`codeFlowLocation.step` is gone from the spec.

@michaelcfanning @EasyRhinoMSFT FYI.
